nodejs:
  image: node:12.17.0-stretch
  stage: build
  artifacts:
    expire_in: 1 day
    paths:
      - rules/static/dist
      - rules/static/bundles
      - rules/static/webpack-stats.prod.json
  before_script:
    - npm install -g npm 
    - npm install -g webpack@3.11
    - npm install node-sass
    - npm install node-gyp
  script:
    - npm install
    - webpack
    - cd hunt
    - npm install
    - npm run build
    - node node_modules/eslint/bin/eslint.js -c .eslintrc .

eslint:
  image: node:12.17.0-stretch
  stage: test
  before_script:
    - cd hunt
    - npm install
    - cd ..
  script:
    - python tests/eslint_check.py $(find hunt -name \*.js |grep -v /node_modules/)

python:
  image: python:2.7.18-stretch
  stage: build
  before_script:
    - python -m pip install --upgrade pip wheel setuptools
    - python -m pip install --upgrade six
    - python -m pip install python-daemon
    - python -m pip install suricatactl
    - python -m pip install django-bootstrap3==11.1.0
    - python -m pip install elasticsearch-curator==5.6
  script:
    - python -m pip install -r requirements.txt

dlint:
  image: python:2.7.18-stretch
  stage: test
  before_script:
    - python -m pip install dlint
  script:
    - python -m flake8 --select=DUO rules
    - python -m flake8 --select=DUO suricata
